### ISSUE TITLE
problem with babel-preset-flow

### ISSUE THREAD

**Issue by skilgoreT** [lifenautjoe/webpack-starter-basic#15]
Following the kickstart instructions results in the below error.

```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "flow" relative to directory "/Users/skelly"
    at /Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/skelly/dev/webpack-starter-basic/node_modules/babel-loader/lib/index.js:50:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js main[1]
C
```

**Comment by lifenautjoe** [comment]
Hi @skilgoreT . 

Will take a look now. Seems like its trying to locate the plugin for type checking flow but which is not used in this project. Any chance you might have a .babelrc in the place you're running the script from?

**Comment by skilgoreT** [comment]
Thanks @lifenautjoe - I had .babelrc in $HOME - removing it fixed the issue -- Thanks!

**Comment by lifenautjoe** [comment]
Glad to help!
